# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

#general pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace 
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

#Flake 8 code linter 
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
 

# Mypy static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy


#isort import sorter
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

# Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black           